name: Trigger Creator

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: write
  workflows: write

jobs:
  update-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_CLASSIC_TOKEN }}  # Use Classic PAT for Git operations

      - name: Enable Main Workflow
        run: gh workflow enable main-runner.yaml
        env:
          GH_TOKEN: ${{ secrets.GH_CLASSIC_TOKEN }}

      - name: Generate Randomized Cron Time
        id: random-cron
        run: |
          # Generate a random hour between 0 and 23
          NEW_HOUR=$((RANDOM % 24))
          
          # Generate a random minute between 0 and 59
          NEW_MINUTE=$((RANDOM % 60))

          # Create new cron expression
          NEW_CRON="$NEW_MINUTE $NEW_HOUR * * *"
          echo "NEW_CRON=$NEW_CRON" >> $GITHUB_ENV

      - name: Update `main-runner.yaml` with New Cron
        run: |
          # Replace the old cron with the new one in main-runner.yaml
          sed -i "s/^    - cron: \".*\"/    - cron: \"${NEW_CRON}\"/" .github/workflows/main-runner.yaml

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git add .github/workflows/main-runner.yaml
          git commit -m "Update main-runner cron to: ${NEW_CRON}"
          git push origin main
